<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuratPerintahSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $now = now();

        DB::table('surat_perintah')->insert([
            [
                'nomor_sp' => '463/PW.02.01/Sekre',
                'tanggal_sp' => '2026-02-10',
                'unit_kerja' => 'Inspektur Pembantu I',
                'lokasi' => 'Kabupaten Sukabumi',
                'nama_pengirim' => 'Dedi Supriyadi',
                'tujuan_transfer' => 'Ahmad Fauzi Rahman',
                'irban_dibayar' => true,
                'rincian_tgl_bayar' => '10 Februari 2026 s.d 14 Februari 2026',
                'keterangan' => 'Melaksanakan Reviu Laporan Keuangan Pemerintah Daerah (LKPD) pada Dinas Bina Marga dan Sumber Daya Air Kabupaten Sukabumi',
                'file_url' => 'sp/463-PW0201.pdf',
                'status_sp' => 'Baru',
                'status' => 'Selesai',
                'pengajuan' => 'Uang Harian, Akomodasi',
                'catatan' => null,
                'dipantau' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nomor_sp' => '509/KPG.03.01/Sekre',
                'tanggal_sp' => '2026-02-25',
                'unit_kerja' => 'Inspektur Pembantu II',
                'lokasi' => 'Kota Depok',
                'nama_pengirim' => 'Rina Marlina',
                'tujuan_transfer' => 'Siti Nurhaliza Putri',
                'irban_dibayar' => false,
                'rincian_tgl_bayar' => '3 Maret 2026',
                'keterangan' => 'Melaksanakan Monitoring dan Evaluasi Penyerapan Anggaran Triwulan I pada Dinas Pendidikan Kota Depok',
                'file_url' => 'sp/509-KPG0301.pdf',
                'status_sp' => 'Baru',
                'status' => 'Draft NPD - PPTK',
                'pengajuan' => 'Transport',
                'catatan' => null,
                'dipantau' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nomor_sp' => '471/PW.02.03/Sekre',
                'tanggal_sp' => '2026-03-12',
                'unit_kerja' => 'Inspektur Pembantu III',
                'lokasi' => 'Kota Bandung',
                'nama_pengirim' => 'Asep Kurniawan',
                'tujuan_transfer' => 'Muhammad Rizky Ramadhan',
                'irban_dibayar' => true,
                'rincian_tgl_bayar' => '12-14 Maret 2026',
                'keterangan' => 'Melaksanakan Audit Kinerja pada Rumah Sakit Umum Daerah Kota Bandung',
                'file_url' => 'sp/471-PW0203.pdf',
                'status_sp' => 'Baru',
                'status' => null,
                'pengajuan' => null,
                'catatan' => null,
                'dipantau' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nomor_sp' => '528/KPG.04.02/Sekre',
                'tanggal_sp' => '2026-04-05',
                'unit_kerja' => 'Inspektur Pembantu IV',
                'lokasi' => 'Kabupaten Bekasi',
                'nama_pengirim' => 'Yayan Sofyan',
                'tujuan_transfer' => 'Dewi Anggraeni Lestari',
                'irban_dibayar' => false,
                'rincian_tgl_bayar' => '5 April 2026 s.d 9 April 2026',
                'keterangan' => 'Melaksanakan Reviu Rencana Kerja Anggaran (RKA) Perubahan pada Dinas Kesehatan Kabupaten Bekasi',
                'file_url' => 'sp/528-KPG0402.pdf',
                'status_sp' => 'Revisi',
                'status' => 'Draft NPD - PPTK',
                'pengajuan' => 'Uang Harian, Akomodasi, Transport',
                'catatan' => 'Menunggu perbaikan lampiran rincian biaya dari PPTK',
                'dipantau' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nomor_sp' => '486/PW.02.05/Sekre',
                'tanggal_sp' => '2026-04-22',
                'unit_kerja' => 'Inspektur Pembantu Investigasi',
                'lokasi' => 'Kota Cimahi',
                'nama_pengirim' => 'Hendra Gunawan',
                'tujuan_transfer' => 'Fitriani Handayani',
                'irban_dibayar' => true,
                'rincian_tgl_bayar' => '22 April 2026',
                'keterangan' => 'Melaksanakan Investigasi atas Pengaduan Masyarakat terkait Pengadaan Barang dan Jasa di Kota Cimahi',
                'file_url' => 'sp/486-PW0205.pdf',
                'status_sp' => 'Baru',
                'status' => 'Verifikasi - Verifikator',
                'pengajuan' => 'Uang Harian',
                'catatan' => null,
                'dipantau' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nomor_sp' => '542/KPG.03.04/Sekre',
                'tanggal_sp' => '2026-05-18',
                'unit_kerja' => 'Sekretariat',
                'lokasi' => 'Kabupaten Garut',
                'nama_pengirim' => 'Nina Kartika',
                'tujuan_transfer' => 'Bambang Wijaya Kusuma',
                'irban_dibayar' => false,
                'rincian_tgl_bayar' => '18 Mei 2026 s.d 20 Mei 2026',
                'keterangan' => 'Melaksanakan Pendampingan Penyusunan Laporan Pertanggungjawaban APBD pada Kabupaten Garut',
                'file_url' => 'sp/542-KPG0304.pdf',
                'status_sp' => 'Baru',
                'status' => null,
                'pengajuan' => null,
                'catatan' => null,
                'dipantau' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nomor_sp' => '497/PW.02.06/Sekre',
                'tanggal_sp' => '2026-06-09',
                'unit_kerja' => 'Subbagian Tata Usaha',
                'lokasi' => 'Kabupaten Sumedang',
                'nama_pengirim' => 'Wawan Setiawan',
                'tujuan_transfer' => 'Ratna Sari Dewi',
                'irban_dibayar' => true,
                'rincian_tgl_bayar' => '29 Juni 2026 s.d 9 Juli 2026',
                'keterangan' => 'Melaksanakan Reviu Laporan Keuangan Semester I pada Badan Pengelolaan Keuangan dan Aset Daerah Kabupaten Sumedang',
                'file_url' => 'sp/497-PW0206.pdf',
                'status_sp' => 'Baru',
                'status' => 'NPD Disetujui - BPP',
                'pengajuan' => 'Uang Harian, Akomodasi',
                'catatan' => null,
                'dipantau' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nomor_sp' => '515/KPG.02.07/Sekre',
                'tanggal_sp' => '2026-07-14',
                'unit_kerja' => 'Inspektur Pembantu I',
                'lokasi' => 'Kota Sukabumi',
                'nama_pengirim' => 'Iwan Ridwan',
                'tujuan_transfer' => 'Agus Salim Nugraha',
                'irban_dibayar' => false,
                'rincian_tgl_bayar' => '15-16 Juli 2026 dan 22 Juli 2026',
                'keterangan' => 'Melaksanakan Reviu Pengadaan Barang dan Jasa pada Dinas Perumahan dan Kawasan Permukiman Kota Sukabumi',
                'file_url' => 'sp/515-KPG0207.pdf',
                'status_sp' => 'Revisi',
                'status' => 'Draft NPD - BPP',
                'pengajuan' => 'Transport',
                'catatan' => 'Revisi nomor SP karena kesalahan penulisan kode unit',
                'dipantau' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
