@extends('layouts.app')

@section('activeNav', 'dashspj')
@section('title', 'Dashboard SPJ Pengawasan')

@section('content')
<style>
  .spj-head h2{margin:0;color:var(--navy);font-size:22px}.spj-head p{margin:4px 0 16px;color:var(--mut)}
  .spj-filter{display:grid;grid-template-columns:1fr 180px 1.4fr auto;gap:12px;align-items:end}.spj-filter label{display:block;font-size:12px;font-weight:700;color:var(--navy);margin-bottom:5px}
  .spj-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:16px 0}.spj-kpi{background:#fff;border:1px solid var(--line);border-radius:13px;padding:15px 16px;box-shadow:var(--shadow)}.spj-kpi small{display:block;color:var(--mut);font-weight:700;text-transform:uppercase}.spj-kpi strong{display:block;color:var(--navy);font-size:22px;margin-top:5px}
  .spj-grid{display:grid;grid-template-columns:minmax(300px,.8fr) minmax(0,1.5fr);gap:16px}.spj-progress{margin:16px 0}.spj-progress-head{display:flex;justify-content:space-between;font-size:13px;margin-bottom:6px}.spj-bar{height:22px;background:#eef2f6;border-radius:6px;overflow:hidden}.spj-bar span{height:100%;display:block;background:linear-gradient(90deg,#3f6187,#15314a)}
  .spj-table-wrap{overflow:auto}.spj-table{min-width:1050px}.spj-status{display:inline-block;padding:4px 9px;border-radius:12px;font-size:11px;font-weight:700}.spj-ok{background:var(--ok-bg);color:var(--ok)}.spj-wait{background:var(--warn-bg);color:var(--warn)}.spj-empty{text-align:center;padding:46px;color:var(--mut)}
  @media(max-width:960px){.spj-grid{grid-template-columns:1fr}.spj-filter{grid-template-columns:1fr 1fr}.spj-kpis{grid-template-columns:1fr 1fr}}@media(max-width:600px){.spj-filter,.spj-kpis{grid-template-columns:1fr}}
</style>
<div class="spj-head"><h2>Dashboard SPJ Pengawasan</h2><p>Status SPJ terpisah dari status NPD. Hanya NPD Selesai pada Program Pengawasan (6.01.02/6.01.03), TA {{ $dashboard['tahun'] }}.</p></div>
<div class="dash-card"><form method="GET" class="spj-filter">
  <div><label for="spj-bidang">Bidang</label><select id="spj-bidang" name="bidang"><option value="">Semua Bidang</option>@foreach($dashboard['pilihan_bidang'] as $bidang)<option @selected($filters['bidang']===$bidang)>{{ $bidang }}</option>@endforeach</select></div>
  <div><label for="spj-status">Status SPJ</label><select id="spj-status" name="status"><option value="">Semua</option><option value="terverifikasi" @selected($filters['status']==='terverifikasi')>Terverifikasi</option><option value="belum" @selected($filters['status']==='belum')>Belum</option></select></div>
  <div><label for="spj-cari">Pencarian</label><input id="spj-cari" name="cari" value="{{ $filters['cari'] }}" placeholder="Nomor NPD/SP, sub kegiatan, uraian"></div>
  <div><button class="btn prim">Terapkan</button> <a class="btn" href="{{ route('dashboard.spj.index') }}">Reset</a></div>
</form></div>
<div class="spj-kpis"><div class="spj-kpi"><small>Total SPJ</small><strong>{{ $dashboard['total'] }}</strong></div><div class="spj-kpi"><small>Terverifikasi</small><strong>{{ $dashboard['terverifikasi'] }}</strong></div><div class="spj-kpi"><small>Belum</small><strong>{{ $dashboard['belum'] }}</strong></div><div class="spj-kpi"><small>Persen Selesai</small><strong>{{ number_format($dashboard['persen'],1,',','.') }}%</strong></div></div>
@if($dashboard['kosong'])<div class="dash-card spj-empty">Belum ada NPD Pengawasan berstatus Selesai untuk filter ini. Status NPD Selesai tidak otomatis berarti SPJ terverifikasi.</div>@else
<div class="spj-grid"><div class="dash-card"><h3 style="margin:0;color:var(--navy)">Rekap per Bidang</h3>@foreach($dashboard['bidang'] as $bidang)<div class="spj-progress"><div class="spj-progress-head"><strong>{{ $bidang['bidang'] }}</strong><span>{{ $bidang['terverifikasi'] }}/{{ $bidang['total'] }} ({{ number_format($bidang['persen'],1,',','.') }}%)</span></div><div class="spj-bar"><span style="width:{{ min(100,$bidang['persen']) }}%"></span></div></div>@endforeach</div>
<div class="dash-card"><h3 style="margin:0;color:var(--navy)">Daftar Detail SPJ</h3><div class="sub">Verifikasi SPJ tidak mengubah status workflow NPD.</div><div class="spj-table-wrap"><table class="realisasi spj-table"><thead><tr><th>Tanggal / Nomor NPD</th><th>Nomor SP</th><th>Bidang</th><th>Sub Kegiatan / Uraian</th><th class="num">Nominal</th><th>Status SPJ</th><th>Aksi</th></tr></thead><tbody>@foreach($dashboard['rows'] as $row)<tr><td>{{ $row['tanggal']->format('d-m-Y') }}<br><strong>{{ $row['nomor_npd'] }}</strong></td><td>{{ $row['nomor_sp'] }}</td><td>{{ $row['bidang'] }}</td><td>{{ $row['sub_kegiatan'] }}<br><small>{{ $row['uraian'] }}</small></td><td class="num">{{ fmt_rupiah($row['nominal']) }}</td><td>@if($row['status_spj']==='terverifikasi')<span class="spj-status spj-ok">TERVERIFIKASI</span><small style="display:block;margin-top:4px">{{ $row['verified_at']->format('d-m-Y H:i') }} · {{ $row['verified_by'] }}</small>@else<span class="spj-status spj-wait">BELUM</span>@endif</td><td>@if($bolehVerifikasi)<form method="POST" action="{{ route('dashboard.spj.verify',$row['id']) }}">@csrf<input type="hidden" name="aksi" value="{{ $row['status_spj']==='terverifikasi'?'batalkan':'verifikasi' }}"><button class="btn {{ $row['status_spj']==='terverifikasi'?'':'prim' }}" onclick="return confirm('{{ $row['status_spj']==='terverifikasi'?'Batalkan verifikasi SPJ ini?':'Verifikasi SPJ ini sebagai selesai?' }}')">{{ $row['status_spj']==='terverifikasi'?'Batalkan':'Verifikasi' }}</button></form>@else<span class="sub">Lihat saja</span>@endif</td></tr>@endforeach</tbody></table></div></div></div>
@endif
@endsection
