@extends('layouts.app')
@section('activeNav', 'invspj')
@section('title', 'Inventarisasi SPJ')
@section('content')
<style>
.inv-head h2{margin:0;color:var(--navy)}.inv-head p{margin:4px 0 16px;color:var(--mut)}.inv-filter{display:grid;grid-template-columns:120px 1.5fr 1fr 1fr 1.2fr auto;gap:10px;align-items:end}.inv-filter label{display:block;font-size:11px;font-weight:700;color:var(--navy);margin-bottom:4px}.inv-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:16px 0}.inv-stat{background:#fff;border:1px solid var(--line);border-radius:12px;padding:15px;box-shadow:var(--shadow)}.inv-stat small{display:block;color:var(--mut);font-weight:700;text-transform:uppercase}.inv-stat strong{display:block;color:var(--navy);font-size:22px;margin-top:4px}.inv-rack{display:flex;gap:12px;align-items:flex-end;overflow-x:auto;padding:22px;background:linear-gradient(#6b4b35 0 8px,#d6b48b 8px 13px,#f4efe8 13px calc(100% - 12px),#6b4b35 calc(100% - 12px));border-radius:12px;min-height:265px}.bantex{width:92px;height:218px;flex:0 0 92px;background:#253f60;border-radius:5px 5px 2px 2px;padding:11px 8px;box-shadow:4px 3px 8px #0004;cursor:pointer;transition:.18s;color:#14263b}.bantex:hover,.bantex.active{transform:translateY(-9px) scale(1.03)}.bx-label{height:160px;background:#f7f1dc;border:2px solid #d7c69b;border-radius:3px;text-align:center;padding:6px 4px}.bx-brand{font-size:9px;color:#a33;font-weight:800}.bx-no{font-size:22px;font-weight:800;margin:4px}.bx-name{font-size:11px;font-weight:800;overflow-wrap:anywhere;max-height:45px;overflow:hidden}.bx-count{font-size:10px;margin-top:7px}.bx-hole{width:22px;height:22px;background:#162a42;border:4px solid #c8b878;border-radius:50%;margin:7px auto}.inv-panels{display:grid;grid-template-columns:1fr 1.6fr;gap:16px;margin-top:16px}.inv-docs{max-height:460px;overflow:auto}.inv-paper{border:1px solid var(--line);border-left:5px solid var(--gold);border-radius:8px;padding:10px;margin:8px 0;cursor:pointer}.inv-paper:hover,.inv-paper.active{background:var(--navy-l)}.inv-detail .li{display:flex;justify-content:space-between;gap:14px;padding:6px 0;border-bottom:1px dashed var(--line)}.inv-detail .k{color:var(--mut)}.inv-detail .v{text-align:right;font-weight:600}.inv-table{overflow:auto}.inv-table table{min-width:1150px}@media(max-width:1000px){.inv-filter{grid-template-columns:1fr 1fr}.inv-stats,.inv-panels{grid-template-columns:1fr}}@media(max-width:600px){.inv-filter,.inv-stats{grid-template-columns:1fr}}
</style>
<div class="inv-head"><h2>Inventarisasi SPJ</h2><p>Rak bantex interaktif dari NPD Selesai pada transaksi Laravel. Data Gaji dan Tunjangan ASN dikecualikan.</p></div>
<div class="dash-card"><form class="inv-filter" method="GET"><div><label>Bulan</label><select name="bulan"><option value="">Semua</option>@foreach($inventaris['pilihan']['bulan'] as $bulan)<option value="{{ $bulan }}" @selected((string)$filters['bulan']===(string)$bulan)>{{ now()->setMonth($bulan)->locale('id')->translatedFormat('F') }}</option>@endforeach</select></div><div><label>Sub Kegiatan</label><select name="sub_kegiatan"><option value="">Semua</option>@foreach($inventaris['pilihan']['sub_kegiatan'] as $v)<option @selected($filters['sub_kegiatan']===$v)>{{ $v }}</option>@endforeach</select></div><div><label>Kode Rekening</label><select name="kode_rekening"><option value="">Semua</option>@foreach($inventaris['pilihan']['kode_rekening'] as $v)<option @selected($filters['kode_rekening']===$v)>{{ $v }}</option>@endforeach</select></div><div><label>Tagging</label><select name="tagging"><option value="">Semua</option>@foreach($inventaris['pilihan']['tagging'] as $v)<option @selected($filters['tagging']===$v)>{{ $v }}</option>@endforeach</select></div><div><label>Pencarian</label><input name="cari" value="{{ $filters['cari'] }}" placeholder="Nomor, penerima, uraian, lokasi"></div><div><button class="btn prim">Terapkan</button> <a class="btn" href="{{ route('inventarisasi-spj.index') }}">Reset</a></div></form></div>
<div class="inv-stats"><div class="inv-stat"><small>Total Dokumen</small><strong>{{ $inventaris['jumlah_dokumen'] }}</strong></div><div class="inv-stat"><small>Jumlah Bantex/Box</small><strong>{{ $inventaris['jumlah_lokasi'] }}</strong></div><div class="inv-stat"><small>Total Nominal NPD Unik</small><strong>{{ fmt_rupiah($inventaris['total_nominal']) }}</strong></div></div>
@if($inventaris['kosong'])<div class="dash-card" style="text-align:center;padding:45px;color:var(--mut)">Tidak ada dokumen sesuai filter.</div>@else
<div class="inv-rack" id="inv-rack">@foreach($inventaris['lokasi'] as $i=>$lokasi)<button type="button" class="bantex" data-location="{{ $i }}"><div class="bx-label"><div class="bx-brand">BANTEX · ARSIP</div><div class="bx-no">{{ str_pad($i+1,2,'0',STR_PAD_LEFT) }}</div><div class="bx-name">{{ $lokasi['lokasi'] }}</div><div class="bx-count">{{ $lokasi['jumlah_dokumen'] }} dok · {{ fmt_rupiah($lokasi['nominal']) }}</div></div><div class="bx-hole"></div></button>@endforeach</div>
<div class="inv-panels"><div class="dash-card"><h3 id="inv-location-title" style="margin:0;color:var(--navy)">Pilih bantex</h3><div class="inv-docs" id="inv-docs"><div class="sub" style="padding:20px 0">Klik satu bantex untuk melihat dokumen.</div></div></div><div class="dash-card inv-detail"><h3 style="margin:0;color:var(--navy)">Detail Dokumen</h3><div id="inv-detail"><div class="sub" style="padding:20px 0">Pilih dokumen pada panel kiri.</div></div></div></div>
<div class="dash-card" style="margin-top:16px"><div class="inv-table"><table class="realisasi"><thead><tr><th>Bulan</th><th>Nomor NPD</th><th>Jenis Dokumen</th><th>Sub Kegiatan</th><th>Kode Rekening</th><th>Tagging</th><th class="num">Nominal</th><th>Penerima</th><th>Lokasi</th></tr></thead><tbody>@foreach($inventaris['rows'] as $row)<tr><td>{{ $row['bulan_label'] }}</td><td>{{ $row['nomor_npd'] }}</td><td>{{ $row['jenis_dokumen'] }}</td><td>{{ $row['sub_kegiatan'] }}</td><td>{{ $row['kode_rekening'] }}</td><td>{{ $row['tagging'] ?: '-' }}</td><td class="num">{{ fmt_rupiah($row['nominal']) }}</td><td>{{ $row['penerima'] }}</td><td>{{ $row['lokasi'] }}</td></tr>@endforeach</tbody></table></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const locations={{ Illuminate\Support\Js::from($inventaris['lokasi']) }},docs=document.getElementById('inv-docs'),detail=document.getElementById('inv-detail'),title=document.getElementById('inv-location-title'),rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0),esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};function showDoc(r){detail.innerHTML=[['Nomor NPD',r.nomor_npd],['Jenis Dokumen',r.jenis_dokumen],['Tanggal',r.tanggal],['Sub Kegiatan',r.sub_kegiatan],['Kode Rekening',r.kode_rekening],['Tagging',r.tagging||'-'],['Uraian',r.uraian],['Nominal',rp(r.nominal)],['Penerima',r.penerima],['Lokasi',r.lokasi],['Catatan Arsip',r.catatan_arsip||'-']].map(x=>'<div class="li"><span class="k">'+esc(x[0])+'</span><span class="v">'+esc(x[1])+'</span></div>').join('')}document.querySelectorAll('[data-location]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-location]').forEach(x=>x.classList.toggle('active',x===b));const l=locations[Number(b.dataset.location)];title.textContent=l.lokasi+' — '+l.jumlah_dokumen+' dokumen';docs.innerHTML=l.dokumen.map((r,i)=>'<div class="inv-paper" data-doc="'+i+'"><strong>'+esc(r.nomor_npd)+'</strong><div class="sub">'+esc(r.jenis_dokumen)+' · '+rp(r.nominal)+'</div><div>'+esc(r.penerima)+'</div></div>').join('');docs.querySelectorAll('[data-doc]').forEach(p=>p.addEventListener('click',()=>{docs.querySelectorAll('[data-doc]').forEach(x=>x.classList.toggle('active',x===p));showDoc(l.dokumen[Number(p.dataset.doc)])}))}))});</script>
@endif
@endsection
